using System;
using System.IO;
using System.Linq;
using System.Threading;
using Creezio.Switcher;

internal static class AssistanceTests
{
    private static void Assert(bool ok,string why){if(!ok)throw new Exception(why);}
    private static void Denied(Action action){try{action();}catch(InvalidOperationException){return;}throw new Exception("Expected rejection");}
    private static object Obj(object value){return Json.Read<object>(Json.Write(value));}
    public static void RunAll(Action<string,Action> check,string root)
    {
        int n=100;
        Func<RemoteTests.Fixture> fixture=()=>new RemoteTests.Fixture(root,++n);
        Func<RemoteTests.Fixture,string,AssistanceTicket> request=(f,id)=>new Assistance(f.Store,f.Fake).Request(id,"shared","existing","Question","Ambiguïté à résoudre","Contexte sans secret",true,CancellationToken.None).GetAwaiter().GetResult();
        check("assistance requires explicit request or enabled configured rule",()=>{var f=fixture();var a=new Assistance(f.Store,f.Fake);Denied(()=>a.Request(Guid.NewGuid().ToString("N"),"shared","existing","title","why","context",false,CancellationToken.None).GetAwaiter().GetResult());Assistance.SaveRule(f.Store,new AssistanceRule{Channel="shared",Enabled=true,Instructions="Ask on ambiguity"});var t=a.Request(Guid.NewGuid().ToString("N"),"shared","existing","title","why","context",false,CancellationToken.None).GetAwaiter().GetResult();Assert(t.State=="pending","not persisted");});
        check("assistance submission is idempotent and scoped to source chat",()=>{var f=fixture();string id=Guid.NewGuid().ToString("N");request(f,id);request(f,id);var a=new Assistance(f.Store,f.Fake);Assert(a.List().Count==1,"duplicate");Denied(()=>a.Authorize(new RelaySession{Channel="shared",Thread="different"},id));Denied(()=>a.Request(id,"shared","existing","changed","why","context",true,CancellationToken.None).GetAwaiter().GetResult());});
        check("assistance answer persists and delivers once after native chat idle",()=>{var f=fixture();var a=new Assistance(f.Store,f.Fake);var t=request(f,Guid.NewGuid().ToString("N"));a.Answer(t.Id,"Précision validée","read");a.Answer(t.Id,"Précision validée","read");Denied(()=>a.Answer(t.Id,"other","read"));a.Pump(CancellationToken.None).Wait();t=a.Read(t.Id);f.Fake.Occupied=true;var e=new RelayEngine(f.Store,f.Fake);e.Process(t.ReplyJob,CancellationToken.None).Wait();Assert(f.Fake.Sends==0,"busy interrupted");f.Fake.Occupied=false;e.Process(t.ReplyJob,CancellationToken.None).Wait();a.Pump(CancellationToken.None).Wait();a.Pump(CancellationToken.None).Wait();Assert(a.Read(t.Id).State=="delivered"&&f.Fake.Sends==1,"duplicate or missing response");});
        check("assistance does not resume a changed channel binding",()=>{var f=fixture();var a=new Assistance(f.Store,f.Fake);var t=request(f,Guid.NewGuid().ToString("N"));a.Answer(t.Id,"ok","read");string other=Path.Combine(f.Channel.Workspace,"different");Directory.CreateDirectory(other);f.Channel.Workspace=other;f.Store.Register(f.Channel);a.Pump(CancellationToken.None).Wait();Assert(f.Store.Count()==0&&a.Read(t.Id).Error!=null,"sent to changed workspace");});
        check("assistance analysis is read only and cannot be duplicated",()=>{var f=fixture();var a=new Assistance(f.Store,f.Fake);var t=request(f,Guid.NewGuid().ToString("N"));string id=a.Analyze(t.Id,"shared",CancellationToken.None).Result;Assert(a.Analyze(t.Id,"shared",CancellationToken.None).Result==id&&f.Store.Count()==1&&f.Store.Message(id).Job.Access=="read","analysis duplication or scope");});
        check("remote assistance requires dedicated right and shared source thread",()=>{var f=fixture();var t=request(f,Guid.NewGuid().ToString("N"));Denied(()=>f.Call(f.Request("assistance_list",new{})));var grants=RemotePeers.Grants(f.Store);grants[0].CanAssist=true;f.Store.WriteRecord("remote-grants.dpapi",grants);Assert(RelayEngine.Rows(f.Call(f.Request("assistance_list",new{}))).Count()==1,"shared ticket absent");grants[0].Threads.Clear();f.Store.WriteRecord("remote-grants.dpapi",grants);Assert(!RelayEngine.Rows(f.Call(f.Request("assistance_list",new{}))).Any(),"private ticket leaked");Denied(()=>f.Call(f.Request("assistance_reply",new{id=t.Id,answer="ok",access="read"})));});
        check("remote assistance reply is idempotent without granting send access",()=>{var f=fixture();var t=request(f,Guid.NewGuid().ToString("N"));var grants=RemotePeers.Grants(f.Store);grants[0].CanAssist=true;grants[0].CanSend=false;f.Store.WriteRecord("remote-grants.dpapi",grants);RelayWorker.Stop(f.Store);var r=f.Request("assistance_reply",new{id=t.Id,answer="ok",access="read"});f.Call(r);f.Call(r);Assert(new Assistance(f.Store,f.Fake).Read(t.Id).State=="answered","answer lost");Denied(()=>f.Call(f.Request("send_message_to_thread",new{threadId="existing",prompt="unauthorized"})));});
        check("hook disabled or unrelated prompt never creates assistance",()=>{var f=fixture();var r=new AssistanceRule{Channel="shared",Enabled=true,Keywords="publish",PromptLength=300};Assistance.SaveRule(f.Store,r);var input=Obj(new{hook_event_name="UserPromptSubmit",session_id="existing",cwd=f.Channel.Workspace,prompt="publish",turn_id="a"});Assert(AssistanceHooks.Evaluate(f.Store,f.Channel.Home,input,CancellationToken.None,f.Fake).Result==null,"disabled ran");r.HookEnabled=true;Assistance.SaveRule(f.Store,r);Assert(!AssistanceHooks.Matches(r,"hello")&&AssistanceHooks.Matches(r,"PUBLISH it"),"keyword match wrong");});
        check("hook holds configured prompts and deduplicates repeated event",()=>{var f=fixture();Assistance.SaveRule(f.Store,new AssistanceRule{Channel="shared",Enabled=true,HookEnabled=true,HoldPrompt=true,Keywords="publish"});var input=Obj(new{hook_event_name="UserPromptSubmit",session_id="existing",cwd=f.Channel.Workspace,prompt="publish",turn_id="a"});var first=Obj(AssistanceHooks.Evaluate(f.Store,f.Channel.Home,input,CancellationToken.None,f.Fake).Result);AssistanceHooks.Evaluate(f.Store,f.Channel.Home,input,CancellationToken.None,f.Fake).Wait();Assert(Json.Str(Json.Get(first,"decision"))=="block"&&new Assistance(f.Store,f.Fake).List().Count==1,"hook not blocking or duplicate");});
        check("hook installation preserves unrelated hooks and never grants trust",()=>{var f=fixture();string file=Path.Combine(f.Channel.Home,"hooks.json");File.WriteAllText(file,"{\"extra\":true,\"hooks\":{\"Stop\":[{\"hooks\":[{\"type\":\"command\",\"command\":\"preserve\"}]}],\"UserPromptSubmit\":[{\"hooks\":[{\"type\":\"command\",\"command\":\"keep\"}]}]}}");AssistanceHooks.Install(f.Store,f.Channel.Home,System.Reflection.Assembly.GetExecutingAssembly().Location);AssistanceHooks.Install(f.Store,f.Channel.Home,System.Reflection.Assembly.GetExecutingAssembly().Location);string text=File.ReadAllText(file);Assert(text.Contains("preserve")&&text.Contains("keep")&&!text.Contains("bypass-hook-trust"),"overwrote existing or granted trust");var hooks=Json.Get(Json.Read<object>(text),"hooks");Assert(RelayEngine.Rows(Json.Get(hooks,"UserPromptSubmit")).SelectMany(g=>RelayEngine.Rows(Json.Get(g,"hooks"))).Count(h=>Json.Str(Json.Get(h,"statusMessage"))=="Account Switcher assistance")==1,"duplicate handler");});
        check("hook exemption requires exact persisted assistance reply",()=>{var f=fixture();var a=new Assistance(f.Store,f.Fake);var t=request(f,Guid.NewGuid().ToString("N"));a.Answer(t.Id,"publish permitted","read");a.Pump(CancellationToken.None).Wait();t=a.Read(t.Id);var m=f.Store.Message(t.ReplyJob);m.State="sending";f.Store.Save(m);Assistance.SaveRule(f.Store,new AssistanceRule{Channel="shared",Enabled=true,HookEnabled=true,HoldPrompt=true,Keywords="publish"});string prompt=RelayEngine.PreparedPrompt(m,f.Channel,f.Channel,RelayPolicies.Load(f.Store));var input=Obj(new{hook_event_name="UserPromptSubmit",session_id="existing",cwd=f.Channel.Workspace,prompt=prompt,turn_id="a"});Assert(AssistanceHooks.Evaluate(f.Store,f.Channel.Home,input,CancellationToken.None,f.Fake).Result==null,"valid reply blocked");input=Obj(new{hook_event_name="UserPromptSubmit",session_id="existing",cwd=f.Channel.Workspace,prompt=prompt+" forged",turn_id="b"});Assert(Json.Str(Json.Get(Obj(AssistanceHooks.Evaluate(f.Store,f.Channel.Home,input,CancellationToken.None,f.Fake).Result),"decision"))=="block","forged marker bypassed rule");});
    }
}
