using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Creezio.Switcher;

internal static class GeneralRelayTests
{
    private static int seq;
    private static void Assert(bool v,string error){if(!v)throw new Exception(error);}
    private static void Throws(Action f){try{f();}catch(InvalidOperationException){return;}throw new Exception("Expected policy rejection");}
    private static object Obj(object value){return Json.Read<object>(Json.Write(value));}
    internal sealed class Adapter : IRelayTransport
    {
        public bool SourceOffline,TargetOffline;
        public int Created,Returned;
        public int WorkSent;
        public string ActiveFlag;
        public bool InProgress;
        public Action SourceReadHook;
        private readonly Dictionary<string,string> markers=new Dictionary<string,string>();
        public string Final="Checked.\nCREEZIO_OUTCOME {\"status\":\"succeeded\"}";
        public string HoldChannel;
        public readonly TaskCompletionSource<bool> Release=new TaskCompletionSource<bool>();
        public void Verify(RelayChannel c){if((SourceOffline&&c.Id.StartsWith("source"))||(TargetOffline&&c.Id.StartsWith("target")))throw new InvalidOperationException("offline");}
        public void VerifySend(RelayChannel c,string t){Verify(c);}
        public async Task<object> Call(RelayChannel c,string tool,object args,CancellationToken token){
            Verify(c);var a=Obj(args);
            if(tool=="create_thread"){Interlocked.Increment(ref Created);markers[c.Id]=Json.Str(Json.Get(a,"prompt")).Split('\n')[0];if(c.Id==HoldChannel)await Release.Task;return Obj(new{threadId=c.Id+"-chat"});}
            if(tool=="send_message_to_thread"){if(c.Id.StartsWith("source"))Interlocked.Increment(ref Returned);else{WorkSent++;markers[c.Id]=Json.Str(Json.Get(a,"prompt")).Split('\n')[0];}return Obj(new{ok=true});}
            string id=Json.Str(Json.Get(a,"threadId"));
            if(c.Id.StartsWith("source")&&SourceReadHook!=null)SourceReadHook();
            string marker;markers.TryGetValue(c.Id,out marker);
            return Obj(new{thread=new{id=id,status=new{activeFlags=ActiveFlag==null?new string[0]:new[]{ActiveFlag}}},page=new{hasMore=false},turns=c.Id.StartsWith("source")?new object[0]:new object[]{new{id="turn-1",status=InProgress?"inProgress":"completed",items=new object[]{new{type="userMessage",content=new[]{new{type="text",text=marker??""}}},new{type="agentMessage",phase="final",text=Final}}}}});
        }
    }
    internal sealed class Fixture
    {
        public RelayStore Store;public RelayPolicy Policy;public Adapter Adapter=new Adapter();public string Folder;
        public Fixture(string root){Folder=Path.Combine(root,"general-"+(++seq));Directory.CreateDirectory(Folder);Store=new RelayStore(Path.Combine(Folder,"store"));foreach(string id in new[]{"source","target","other"})Store.Register(new RelayChannel{Id=id,Name=id,Home=Folder,AccountKey=id,AnchorThreadId=id+"-chat",Workspace=Folder,Enabled=true});Policy=new RelayPolicy();Policy.Projects.Add(new RelayProject{Id="sample",Workspace=Folder});Policy.Agents.Add(new RelayAgent{Channel="target",AutoRoute=true,Capabilities="review,private-db"});Policy.Agents.Add(new RelayAgent{Channel="other",AutoRoute=true,Capabilities="review"});Save();}
        public void Save(){RelayPolicies.Save(Store,Policy);}
        public RelayJobSpec Spec(){return new RelayJobSpec{From="source",Project="sample",Title="Review prepared files",Prompt="Review only",Access="read",ExplicitDelegation=true,Capabilities="review",ReturnToSource=true};}
        public RelayMessage Submit(RelayJobSpec spec=null){return new RelayRouter(Store,Adapter,a=>50).Submit(spec??Spec(),"source-chat",CancellationToken.None).GetAwaiter().GetResult();}
        public RelayMessage Run(RelayMessage m){var engine=new RelayEngine(Store,Adapter,(h,t)=>"full-access");for(int i=0;i<3;i++){engine.Process(m.Id,CancellationToken.None).GetAwaiter().GetResult();m=Store.Message(m.Id);if(m.State!="queued"||m.DispatchPhase!="work"||m.Error!=null)break;}return m;}
    }
    public static void RunAll(Action<string,Action> check,string root)
    {
        check("new contracts cannot be consumed by a v0.4 directory scan",()=>{var f=new Fixture(root);var m=f.Submit();Assert(File.Exists(Path.Combine(f.Store.Root,"jobs-v4",m.Id+".dpapi"))&&!File.Exists(Path.Combine(f.Store.Root,"messages",m.Id+".dpapi")),"legacy pump can consume new jobs");Assert(new RelayStore(f.Store.Root).Message(m.Id).Job!=null,"new contract not persistent");});
        check("cross-runtime retry compares persisted contract without sending twice",()=>{var f=new Fixture(root);var spec=f.Spec();spec.Prompt="Revue : é & < > ' ";var m=f.Submit(spec);m.SubmissionHash="another-runtime-encoding";f.Store.Save(m);Assert(f.Submit(spec).Id==m.Id&&f.Store.Count()==1,"retry duplicated");spec.Prompt="changed";Throws(()=>f.Submit(spec));Assert(f.Store.Count()==1,"changed payload accepted");});
        check("manual worker stop survives automatic ensure",()=>{var f=new Fixture(root);RelayWorker.Stop(f.Store);RelayWorker.Ensure(f.Store);Assert(RelayWorker.Paused(new RelayStore(f.Store.Root))&&!RelayWorker.Running(f.Store),"automatic restart ignored manual stop");});
        check("configured chat reuse preserves destination and avoids a second creation",()=>{var f=new Fixture(root);f.Policy.Agents[0].ReuseConversation=true;f.Save();var s=f.Spec();s.To="target";var first=f.Run(f.Submit(s));var next=f.Spec();next.To="target";var second=f.Run(f.Submit(next));Assert(first.TargetThreadId==second.TargetThreadId&&f.Adapter.Created==1&&f.Adapter.WorkSent==2&&second.Outcome=="succeeded","ready chat not reused");});
        check("automatic explicit target still respects configured rule destinations",()=>{var f=new Fixture(root);f.Policy.Projects[0].Delegation="rules";f.Policy.Rules.Add(new RelayRule{Id="only-other",Project="sample",Targets="other"});f.Save();var s=f.Spec();s.ExplicitDelegation=false;s.To="target";Throws(()=>f.Submit(s));});
        check("metadata cache invalidates after another store writes and is not mutable shared state",()=>{var f=new Fixture(root);var m=f.Submit();var summary=f.Store.Messages()[0];summary.State="forged";Assert(f.Store.Messages()[0].State=="queued","cache mutated");m.State="cancelled";new RelayStore(f.Store.Root).Save(m);Assert(f.Store.Messages()[0].State=="cancelled","stale cached state");});
        check("relay metadata tolerates a transient Windows replacement lock",()=>{var f=new Fixture(root);var m=f.Submit();Task writing;using(var held=new FileStream(Path.Combine(f.Store.Root,"jobs-v4",m.Id+".dpapi"),FileMode.Open,FileAccess.Read,FileShare.ReadWrite)){m.Error="updated";writing=Task.Run(()=>f.Store.Save(m));Thread.Sleep(80);}writing.GetAwaiter().GetResult();Assert(f.Store.Message(m.Id).Error=="updated","metadata update lost");});
        check("uncertain reconciliation is bounded and spaced",()=>{var m=new RelayMessage{State="uncertain",ReconcileAttempts=1,ReconcileAfterUtc=DateTime.UtcNow.AddMinutes(1).ToString("o")};Assert(!RelayEngine.ReconcileDue(m),"busy reconciliation");m.ReconcileAfterUtc=null;Assert(RelayEngine.ReconcileDue(m),"due reconciliation missed");m.ReconcileAttempts=3;Assert(!RelayEngine.ReconcileDue(m),"unbounded reconciliation");});
        check("private owner low quota waits without redirecting to an unauthorized account",()=>{var f=new Fixture(root);f.Policy.Resources.Add(new RelayResource{Id="private",Project="sample",Channels="target",Capabilities="private-db"});f.Save();var s=f.Spec();s.Resource="private";var m=new RelayRouter(f.Store,f.Adapter,a=>a=="target"?0:100).Submit(s,"source-chat",CancellationToken.None).GetAwaiter().GetResult();Assert(m.TargetChannelId=="target"&&m.RoutingReason.Contains("quota"),"owner bypassed");f.Policy.Agents[0].AllowUnknownQuota=false;f.Save();m=f.Run(m);Assert(m.State=="queued"&&m.BlockReason=="quota"&&f.Adapter.Created==0,"missing quota dispatched");});
        check("rechecking a delivered failure never repeats the return",()=>{var f=new Fixture(root);var s=f.Spec();s.To="target";f.Adapter.Final="CREEZIO_OUTCOME {\"status\":\"failed\"}";var m=f.Run(f.Submit(s));m.State="failed";f.Store.Save(m);f.Store.Recheck(m.Id);m=f.Run(m);Assert(f.Adapter.Returned==1&&m.ReturnState=="delivered","duplicate failure return");});
        check("new chat preflight blocks permission mismatch before sending work",()=>{var f=new Fixture(root);var s=f.Spec();s.To="target";var m=f.Submit(s);string mode="workspace-write / on-request";var engine=new RelayEngine(f.Store,f.Adapter,(h,t)=>t=="target-chat"?mode:"full-access");var c=f.Store.Channel("target");c.AnchorThreadId="anchor-full";f.Store.Register(c);engine.Process(m.Id,CancellationToken.None).GetAwaiter().GetResult();m=f.Store.Message(m.Id);Assert(m.State=="waiting"&&m.DispatchPhase=="preflight"&&m.BlockReason=="permissions"&&f.Adapter.WorkSent==0,"work sent before permission check");Assert(!RelayEngine.Preflight(m).Contains(s.Prompt),"work leaked into preflight");mode="full-access";engine.Process(m.Id,CancellationToken.None).GetAwaiter().GetResult();engine.Process(m.Id,CancellationToken.None).GetAwaiter().GetResult();Assert(f.Store.Message(m.Id).State=="completed"&&f.Adapter.Created==1&&f.Adapter.WorkSent==1,"authorized preflight failed to resume once");});
        check("unknown new chat permissions never dispatch work",()=>{var f=new Fixture(root);var m=f.Submit();new RelayEngine(f.Store,f.Adapter,(h,t)=>"unknown").Process(m.Id,CancellationToken.None).GetAwaiter().GetResult();Assert(f.Store.Message(m.Id).BlockReason=="permissions"&&f.Adapter.WorkSent==0,"unknown permissions accepted");});
        check("pending Codex approval is visible without being answered",()=>{var f=new Fixture(root);var s=f.Spec();s.To="target";var m=f.Submit(s);m.State="waiting";m.TargetThreadId="target-chat";f.Store.Save(m);f.Adapter.InProgress=true;f.Adapter.ActiveFlag="waitingOnApproval";m=f.Run(m);Assert(m.BlockReason=="approval"&&m.State=="waiting"&&f.Adapter.Returned==0&&f.Adapter.WorkSent==0,"approval hidden or acknowledged");});
        check("MCP lifecycle exposes tools without impersonating a chat",()=>{var f=new Fixture(root);var server=new RelayMcp(f.Store,f.Folder);var initial=server.Handle(Obj(new{jsonrpc="2.0",id=1,method="initialize",@params=new{protocolVersion="2025-11-25"}}),CancellationToken.None).GetAwaiter().GetResult();Assert(Json.Get(Obj(initial),"result")!=null,"initialize failed");var tools=server.Handle(Obj(new{jsonrpc="2.0",id=2,method="tools/list"}),CancellationToken.None).GetAwaiter().GetResult();Assert(RelayEngine.Rows(Json.Get(Json.Get(Obj(tools),"result"),"tools")).Count()>=9,"tools missing");var denied=server.Handle(Obj(new{jsonrpc="2.0",id=3,method="tools/call",@params=new{name="list_agents",arguments=new{session="invented"}}}),CancellationToken.None).GetAwaiter().GetResult();Assert(Object.Equals(Json.Get(Json.Get(Obj(denied),"result"),"isError"),true),"unbound call allowed");});
        check("MCP rejects calls before initialization",()=>{var f=new Fixture(root);var server=new RelayMcp(f.Store,f.Folder);var r=server.Handle(Obj(new{jsonrpc="2.0",id=1,method="tools/list"}),CancellationToken.None).GetAwaiter().GetResult();Assert(Json.Get(Obj(r),"error")!=null,"uninitialized client accepted");});
        check("chat sessions reject wrong profile and changed account",()=>{var f=new Fixture(root);string key=new string('a',64);var s=new RelaySession{Token=key,Channel="source",Thread="source-chat",Home=f.Folder,Account="source",Expires=DateTime.UtcNow.AddDays(1).ToString("o")};f.Store.WriteRecord("session-"+key+".dpapi",s);Assert(RelaySessions.Resolve(f.Store,key,f.Folder,false).Thread==s.Thread,"session lost");Throws(()=>RelaySessions.Resolve(f.Store,key,root,false));s.Account="other";f.Store.WriteRecord("session-"+key+".dpapi",s);Throws(()=>RelaySessions.Resolve(f.Store,key,f.Folder,false));});
        check("chat session cannot inspect another conversation's jobs",()=>{var f=new Fixture(root);var m=f.Submit();Throws(()=>RelaySessions.Authorize(f.Store,new RelaySession{Channel="source",Thread="other-chat"},m.Id,false));});
        check("structured result stays pending until destination turn finishes",()=>{var f=new Fixture(root);var s=f.Spec();s.To="target";var m=f.Submit(s);m.TargetThreadId="target-chat";m.State="waiting";f.Store.Save(m);f.Store.Report(m,new RelaySession{Channel="target",Thread="target-chat"},"succeeded",new string('r',30000),new Dictionary<string,string>());Assert(f.Store.Message(m.Id).State=="waiting"&&f.Adapter.Returned==0,"report prematurely released execution");m=f.Run(m);Assert(m.Result.Length==30000&&m.Outcome=="succeeded"&&m.ReturnState=="delivered","long result lost");});
        check("source cannot forge recipient's structured result",()=>{var f=new Fixture(root);var m=f.Submit();Throws(()=>f.Store.Report(m,new RelaySession{Channel="source",Thread="source-chat"},"succeeded","forged",new Dictionary<string,string>()));});
        check("preflight chat cannot report success before receiving the work",()=>{var f=new Fixture(root);var m=f.Submit();m.State="waiting";m.DispatchPhase="preflight";m.TargetThreadId="target-chat";Throws(()=>f.Store.Report(m,new RelaySession{Channel=m.TargetChannelId,Thread="target-chat"},"succeeded","premature",new Dictionary<string,string>()));});
        check("agent discovery excludes resources of projects unavailable to the source",()=>{var f=new Fixture(root);f.Policy.Projects[0].SourceChannels="other";f.Policy.Resources.Add(new RelayResource{Id="private",Project="sample",Channels="target"});f.Save();var view=Obj(new RelayRouter(f.Store,f.Adapter,a=>50).Describe("source"));Assert(!RelayEngine.Rows(Json.Get(view,"projects")).Any()&&!RelayEngine.Rows(Json.Get(view,"resources")).Any(),"out of scope resource metadata exposed");});
        check("queued cancellation is durable and returns its outcome",()=>{var f=new Fixture(root);var m=f.Submit();f.Store.RequestCancel(m.Id);m=f.Run(m);Assert(m.State=="cancelled"&&m.ReturnState=="delivered"&&f.Adapter.Created==0,"cancelled work ran");});
        check("running cancellation never falsely claims a stopped turn",()=>{var f=new Fixture(root);var m=f.Submit();m.State="waiting";f.Store.Save(m);f.Store.RequestCancel(m.Id);m=f.Store.Message(m.Id);Assert(m.State=="waiting"&&m.CancellationRequested,"cancellation falsely completed");});
        check("configurable relay preserves encrypted policy and explicit default",()=>{var f=new Fixture(root);Assert(RelayPolicies.Load(f.Store).Projects[0].Delegation=="explicit","automatic delegation default");Assert(!System.Text.Encoding.UTF8.GetString(File.ReadAllBytes(Path.Combine(f.Store.Root,"policy-v2.dpapi"))).Contains("private-db"),"policy leaked");});
        check("unknown policy version is preserved and rejected",()=>{var f=new Fixture(root);f.Store.WriteRecord("policy-v2.dpapi",new RelayPolicy{Version=999});Throws(()=>RelayPolicies.Load(f.Store));Assert(File.Exists(Path.Combine(f.Store.Root,"policy-v2.dpapi")),"policy deleted");});
        check("generic task contains no provider-specific publishing instruction",()=>{var f=new Fixture(root);var m=f.Submit();string text=RelayEngine.Envelope(m,f.Store.Channel("source"));Assert(!text.Contains("Sites")&&!text.Contains("project_id"),"provider hardcoded");});
        check("automatic delegation requires a configured project rule",()=>{var f=new Fixture(root);var s=f.Spec();s.ExplicitDelegation=false;Throws(()=>f.Submit(s));f.Policy.Projects[0].Delegation="rules";f.Policy.Rules.Add(new RelayRule{Id="review",Project="sample",Task="general",Targets="target"});f.Save();Assert(f.Submit(s).TargetChannelId=="target","configured delegation failed");});
        check("private resource routes only to its configured owner",()=>{var f=new Fixture(root);f.Policy.Resources.Add(new RelayResource{Id="private",Project="sample",Channels="target",Capabilities="private-db"});f.Save();var s=f.Spec();s.Resource="private";Assert(f.Submit(s).TargetChannelId=="target","wrong owner");s.Id=null;s.To="other";Throws(()=>f.Submit(s));});
        check("disabled agent cannot receive explicit tasks",()=>{var f=new Fixture(root);f.Policy.Agents[0].Enabled=false;f.Save();var s=f.Spec();s.To="target";Throws(()=>f.Submit(s));});
        check("task type and project scopes constrain explicit routing",()=>{var f=new Fixture(root);f.Policy.Agents[0].Tasks="test";f.Save();var s=f.Spec();s.To="target";Throws(()=>f.Submit(s));});
        check("unknown capabilities cannot be invented by automatic routing",()=>{var f=new Fixture(root);var s=f.Spec();s.Capabilities="unknown-private-tool";Throws(()=>f.Submit(s));});
        check("submission idempotency includes resource and permissions",()=>{var f=new Fixture(root);var s=f.Spec();var first=f.Submit(s);Assert(f.Submit(s).Id==first.Id&&f.Store.Messages().Count==1,"duplicate submit");s.Access="external";Throws(()=>f.Submit(s));});
        check("policy changes are checked again before execution",()=>{var f=new Fixture(root);var s=f.Spec();s.To="target";var m=f.Submit(s);f.Policy.Agents[0].Enabled=false;f.Save();m=f.Run(m);Assert(m.State=="queued"&&f.Adapter.Created==0,"stale policy allowed dispatch");});
        check("file manifest rejects changed files before dispatch",()=>{var f=new Fixture(root);File.WriteAllText(Path.Combine(f.Folder,"ready.txt"),"ready");var s=f.Spec();s.Files.Add("ready.txt","bad-hash");Throws(()=>f.Submit(s));Assert(f.Store.Messages().Count==0,"invalid manifest queued");});
        check("manifest cannot escape workspace",()=>{var f=new Fixture(root);var s=f.Spec();s.Files.Add("../outside","x");Throws(()=>f.Submit(s));});
        check("new tasks record declared outcome separately from transport",()=>{var f=new Fixture(root);var m=f.Run(f.Submit());Assert(m.State=="completed"&&m.Outcome=="succeeded"&&m.ReturnState=="delivered","structured outcome missing");Assert(m.Events.Count>=3,"timeline missing");});
        check("ordinary final text is not automatically business success",()=>{Assert(RelayEngine.Outcome("I could not complete this") == "unverified","false success");Assert(RelayEngine.Outcome("CREEZIO_OUTCOME {\"status\":\"blocked\"}")=="blocked","blocked lost");});
        check("verified source may close while target runs and result waits",()=>{var f=new Fixture(root);var s=f.Spec();s.To="target";var m=f.Submit(s);f.Adapter.SourceOffline=true;m=f.Run(m);Assert(m.State=="completed"&&m.ReturnState=="pending","source closure blocked execution");f.Adapter.SourceOffline=false;f.Adapter.TargetOffline=true;m=f.Run(m);Assert(m.ReturnState=="delivered"&&f.Adapter.Created==1,"closed target blocked stored return");});
        check("dependency requires success and failed dependency never dispatches",()=>{var f=new Fixture(root);var first=f.Submit();f.Adapter.Final="CREEZIO_OUTCOME {\"status\":\"failed\"}";first=f.Run(first);var s=f.Spec();s.DependsOn.Add(first.Id);var second=f.Run(f.Submit(s));Assert(second.State=="queued"&&f.Adapter.Created==1,"failed dependency ignored");});
        check("dependency success allows next job",()=>{var f=new Fixture(root);var first=f.Run(f.Submit());var s=f.Spec();s.DependsOn.Add(first.Id);Assert(f.Run(f.Submit(s)).Outcome=="succeeded","dependency never resumed");});
        check("foreign conversation cannot inject dependency",()=>{var f=new Fixture(root);var m=f.Submit();m.SourceThreadId="someone-else";f.Store.Save(m);var s=f.Spec();s.DependsOn.Add(m.Id);Throws(()=>f.Submit(s));});
        check("expired queued task returns a failure without execution",()=>{var f=new Fixture(root);var m=f.Submit();m.DeadlineUtc=DateTime.UtcNow.AddMinutes(-1).ToString("o");f.Store.Save(m);m=f.Run(m);Assert(m.State=="failed"&&m.Outcome=="expired"&&f.Adapter.Created==0&&m.ReturnState=="delivered","expired task executed");});
        check("resource and workspace locks span channels",()=>{var f=new Fixture(root);var first=f.Submit();first.State="waiting";first.Job.Access="write";f.Store.Save(first);var s=f.Spec();s.To=first.TargetChannelId=="target"?"other":"target";var second=f.Run(f.Submit(s));Assert(second.State=="queued"&&f.Adapter.Created==0,"shared write workspace raced");});
        check("slow remote call does not hold global dispatch lock",()=>{
            var f=new Fixture(root);var first=f.Submit();f.Adapter.HoldChannel=first.TargetChannelId;
            string secondFolder=Path.Combine(f.Folder,"second");Directory.CreateDirectory(secondFolder);
            foreach(string id in new[]{"source-two","target-two"})f.Store.Register(new RelayChannel{Id=id,Name=id,Home=f.Folder,AccountKey=id,AnchorThreadId=id+"-chat",Workspace=secondFolder,Enabled=true});
            var second=f.Store.Enqueue("source-two","source-two-chat","target-two","Other project","Review",null,false,null);
            var engine=new RelayEngine(f.Store,f.Adapter);var pending=engine.Process(first.Id,CancellationToken.None);
            var independent=engine.Process(second.Id,CancellationToken.None);bool completed=independent.Wait(3000);f.Adapter.Release.TrySetResult(true);pending.GetAwaiter().GetResult();
            Assert(completed&&f.Store.Message(second.Id).State=="completed","slow channel blocked another project");
        });
    }
}
