using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using Creezio.Switcher;

internal static class ProductTests
{
    private static void Assert(bool value,string error){if(!value)throw new Exception(error);}
    private static void Reject(Action action){try{action();}catch(InvalidOperationException){return;}throw new Exception("Expected rejection");}
    public static void RunAll(Action<string,Action> check,string root)
    {
        check("display preserves the reset threshold decimal",()=>{Assert(ProductUx.Percent(1.4)==1.4.ToString("0.0")+" %","rounded down to threshold");Assert(ProductUx.Percent(null)=="—","unknown invented");});
        check("new install asks users to choose automatic reset while legacy setting survives",()=>{string path=Path.Combine(root,"fresh-settings");var vault=new Vault(path);Assert(!vault.LoadSettings().AutoResetCredits,"fresh automatic spend");File.WriteAllText(Path.Combine(path,"settings.json"),"{}");Assert(vault.LoadSettings().AutoResetCredits,"legacy default changed");});
        check("ready agent outranks any numeric rule priority",()=>{var f=new GeneralRelayTests.Fixture(root);f.Policy.Rules.Add(new RelayRule{Id="huge",Targets="target",Priority=Int32.MaxValue});f.Policy.Rules.Add(new RelayRule{Id="normal",Targets="other"});f.Save();f.Adapter.TargetOffline=true;var p=new RelayRouter(f.Store,f.Adapter,a=>50).Preview(f.Spec());Assert(p[0].Channel=="other"&&p[0].Ready,"offline priority won");});
        check("routing simulation never sends or persists a task",()=>{var f=new GeneralRelayTests.Fixture(root);new RelayRouter(f.Store,f.Adapter,a=>50).Preview(f.Spec());Assert(f.Store.Messages().Count==0&&f.Adapter.Created==0,"simulation executed");});
        check("configuration references are validated before save",()=>{var f=new GeneralRelayTests.Fixture(root);f.Policy.Resources.Add(new RelayResource{Id="private",Project="sample",Channels="missing"});Reject(()=>RelayPolicies.ValidateReferences(f.Policy,f.Store));});
        check("configuration export excludes account credentials and can be imported",()=>{var f=new GeneralRelayTests.Fixture(root);string text=RelayPolicies.Export(f.Policy);Assert(!text.Contains("AuthJson")&&!text.Contains("access_token"),"secret export");Assert(RelayPolicies.Import(text).Agents.Count==2,"roundtrip");});
        check("configuration undo restores previous values",()=>{var f=new GeneralRelayTests.Fixture(root);f.Policy.MaxParallel=7;f.Save();RelayPolicies.Restore(f.Store);Assert(RelayPolicies.Load(f.Store).MaxParallel==4,"undo failed");});
        check("automatic rules are rechecked after queue admission",()=>{var f=new GeneralRelayTests.Fixture(root);f.Policy.Projects[0].Delegation="rules";f.Policy.Rules.Add(new RelayRule{Id="first",Targets="target"});f.Save();var spec=f.Spec();spec.ExplicitDelegation=false;spec.To="target";var m=f.Submit(spec);f.Policy.Rules.Clear();f.Save();m=f.Run(m);Assert(f.Adapter.Created==0&&m.BlockReason=="policy","revoked rule executed");});
        check("concurrency limit covers multiple agents on one account",()=>{var f=new GeneralRelayTests.Fixture(root);f.Policy.MaxPerAccount=1;f.Policy.MaxParallel=8;var a=f.Submit();var b=f.Submit();a.State="waiting";a.TargetChannelId="other";a.TargetAccountKey=b.TargetAccountKey;string reason=RelayEngine.WaitReason(b,f.Policy,new List<RelayMessage>{a,b});Assert(reason.Contains("compte"),"shared account not bounded");});
        check("queued rerouting respects explicit targets and started chats",()=>{var f=new GeneralRelayTests.Fixture(root);f.Policy.Projects[0].ReassignQueued=true;f.Save();var spec=f.Spec();spec.To="target";var m=f.Submit(spec);f.Adapter.TargetOffline=true;Assert(!new RelayRouter(f.Store,f.Adapter,a=>50).Reassign(m,f.Policy),"explicit target moved");m.Job.To=null;m.TargetThreadId="already-created";Assert(!new RelayRouter(f.Store,f.Adapter,a=>50).Reassign(m,f.Policy),"started chat moved");});
        check("unstarted automatic task can move to a ready authorized agent",()=>{var f=new GeneralRelayTests.Fixture(root);f.Policy.Projects[0].ReassignQueued=true;f.Save();var m=f.Submit();m.TargetChannelId="target";m.TargetAccountKey="target";f.Store.Save(m);f.Adapter.TargetOffline=true;Assert(new RelayRouter(f.Store,f.Adapter,a=>50).Reassign(m,f.Policy)&&m.TargetChannelId=="other","no failover");});
        check("pause preserves queued work without creating a chat",()=>{var f=new GeneralRelayTests.Fixture(root);var m=f.Submit();RelayDispatch.Set(f.Store,"paused");m=f.Run(m);Assert(m.State=="queued"&&f.Adapter.Created==0,"paused dispatch");RelayDispatch.Set(f.Store,"running");m=f.Run(m);Assert(m.State=="completed","resume failed");});
        check("drain excludes new groups and permits accepted descendants",()=>{var f=new GeneralRelayTests.Fixture(root);var m=f.Submit();RelayDispatch.Set(f.Store,"drain");var n=f.Submit();Assert(RelayDispatch.AllowsStart(f.Store,m)&&!RelayDispatch.AllowsStart(f.Store,n),"drain boundary");n.RootJobId=m.Id;Assert(RelayDispatch.AllowsStart(f.Store,n),"accepted descendant blocked");});
        check("manual result does not restart the source agent",()=>{var f=new GeneralRelayTests.Fixture(root);f.Policy.Projects[0].ReturnMode="manual";f.Save();var m=f.Run(f.Submit());Assert(m.State=="completed"&&m.ReturnState=="manual"&&f.Adapter.Returned==0,"manual result delivered");});
        check("batch result restarts source once and marks all receipts",()=>{var f=new GeneralRelayTests.Fixture(root);f.Policy.Projects[0].ReturnMode="batch";f.Save();var a=f.Submit();var b=f.Submit();foreach(var m in new[]{a,b}){m.State="completed";m.CompletedUtc=DateTime.UtcNow.AddMinutes(-5).ToString("o");m.Outcome="succeeded";m.Result="Reviewed";m.ReturnState="pending";f.Store.Save(m);}f.Run(a);Assert(f.Adapter.Returned==1&&f.Store.Message(a.Id).ReturnState=="delivered"&&f.Store.Message(b.Id).ReturnState=="delivered","not batched");});
        check("job filters isolate blocked work and support case-insensitive search",()=>{var rows=new[]{new RelayMessage{Title="Build Alpha",State="queued",BlockReason="quota"},new RelayMessage{Title="Review",State="completed"}};Assert(RelayForm.Filter(rows,"ALPHA",1).Count()==1&&RelayForm.Filter(rows,"",3).Count()==1,"filters");});
        check("cancel guidance never claims an active turn was stopped",()=>{var m=new RelayMessage{State="waiting",CancellationRequested=true};Assert(ProductUx.JobState(m).Contains("Codex")&&ProductUx.Resolution(m).Contains("reste actif"),"false cancellation");});
        check("reset trigger can select weekly versus session windows",()=>{var p=new Profile{ResetThreshold=5,ResetWindow="weekly",Quotas=new List<QuotaBucket>{new QuotaBucket{Name="codex",Primary=new QuotaWindow{Minutes=300,Remaining=0},Secondary=new QuotaWindow{Minutes=10080,Remaining=6}}}};Assert(!ResetPolicy.Low(p,DateTime.UtcNow),"wrong window");p.Quotas[0].Secondary.Remaining=5;Assert(ResetPolicy.Low(p,DateTime.UtcNow),"exact custom threshold missed");});
        check("invalid reset policy never persists",()=>{var f=new GeneralRelayTests.Fixture(root);Reject(()=>UsageCoordinator.SavePolicies(f.Store,new UsagePolicies{Accounts=new List<AccountUsagePolicy>{new AccountUsagePolicy{Account="a",Threshold=Double.NaN}}}));Assert(!File.Exists(Path.Combine(f.Store.Root,"usage-policy.dpapi")),"invalid persisted");});
        check("quota cache excludes credentials and retains reset intent across restarts",()=>{var f=new GeneralRelayTests.Fixture(root);var p=new Profile{Key="example",AuthJson="secret-test",QuotaTimeUtc=DateTime.UtcNow.ToString("o"),ResetAttempt=new ResetAttempt{IdempotencyKey="same-key",State="pending"}};UsageCoordinator.Cache(f.Store,p);var cached=new RelayStore(f.Store.Root).ReadRecord<Profile>(RelayQuota.Name(p.Key));Assert(cached.AuthJson==null&&cached.ResetAttempt.IdempotencyKey=="same-key","cache secret or lost intent");});
        check("reset history stores transitions without duplicate polls",()=>{var f=new GeneralRelayTests.Fixture(root);var p=new Profile{Key="example",ResetAttempt=new ResetAttempt{IdempotencyKey="one",State="pending"}};UsageCoordinator.Cache(f.Store,p);UsageCoordinator.Cache(f.Store,p);p.ResetAttempt.State="recovered";UsageCoordinator.Cache(f.Store,p);Assert(f.Store.ReadRecord<UsageHistory>("reset-history-"+RelayReturns.Key(p.Key)+".dpapi").Events.Count==2,"duplicate history");});
        check("isolated workspace requires explicit project authorization",()=>{var f=new GeneralRelayTests.Fixture(root);string isolated=Path.Combine(f.Folder,"isolated");Directory.CreateDirectory(isolated);var target=f.Store.Channel("target");target.Workspace=isolated;f.Store.Register(target);Reject(()=>RelayRouter.ValidateDestination(f.Policy,f.Store.Channel("source"),target,f.Spec()));f.Policy.Projects[0].WorkspaceMode="isolated";f.Policy.Projects[0].AllowedWorkspaces=isolated;f.Save();var s=f.Spec();s.To="target";Assert(f.Submit(s).TargetWorkspace==isolated,"isolated target lost");});
        check("artifact manifest catches a changed file",()=>{var f=new GeneralRelayTests.Fixture(root);string path=Path.Combine(f.Folder,"file.txt");File.WriteAllText(path,"before");var manifest=WorkspaceService.Manifest(f.Folder,new[]{path});File.WriteAllText(path,"after");Reject(()=>RelayPolicies.VerifyFiles(f.Folder,manifest));});
        check("manual mode also suppresses failure delivery",()=>{var f=new GeneralRelayTests.Fixture(root);f.Policy.Projects[0].ReturnMode="manual";f.Save();var m=f.Submit();m.DeadlineUtc=DateTime.UtcNow.AddMinutes(-1).ToString("o");f.Store.Save(m);m=f.Run(m);Assert(m.State=="failed"&&m.ReturnState=="manual"&&f.Adapter.Returned==0,"failure restarted source");});
        check("batch cannot mix different pinned identities",()=>{var f=new GeneralRelayTests.Fixture(root);var a=f.Submit();var b=f.Submit();Assert(RelayReturns.SameSource(a,b),"same identity rejected");b.SourceAccountKey="changed";Assert(!RelayReturns.SameSource(a,b),"account mismatch batched");b.SourceAccountKey=a.SourceAccountKey;b.SourceHome=Path.Combine(f.Folder,"different");Assert(!RelayReturns.SameSource(a,b),"profile mismatch batched");});
        check("catalog rebuild recovers an interrupted index write",()=>{var f=new GeneralRelayTests.Fixture(root);var m=f.Submit();f.Store.WriteRecord("catalog-dirty.dpapi",new CatalogHeader());var reopened=new RelayStore(f.Store.Root);Assert(reopened.Count()==1&&reopened.ActiveMessages()[0].Id==m.Id,"index recovery lost job");});
        check("catalog readers wait for an active writer instead of killing the worker",()=>{var f=new GeneralRelayTests.Fixture(root);f.Submit();System.Threading.Tasks.Task<int> read;using(f.Store.Lease("catalog")){f.Store.WriteRecord("catalog-dirty.dpapi",new CatalogHeader());read=System.Threading.Tasks.Task.Run(()=>new RelayStore(f.Store.Root).ActiveMessages().Count);Thread.Sleep(150);Assert(!read.IsCompleted,"reader bypassed the write transaction");}Assert(read.GetAwaiter().GetResult()==1,"writer released but read failed");});
        check("catalog pages never hydrate private prompt or result text",()=>{var f=new GeneralRelayTests.Fixture(root);var m=f.Submit();m.Result="private-result";f.Store.Save(m);var page=f.Store.Query(null,0,1)[0];Assert(page.Prompt==null&&page.Result==null&&page.Job.Prompt==null&&f.Store.Message(m.Id).Result=="private-result","history copied full text");});
        check("configuration template is opt-in and never invents account defaults",()=>{var f=new GeneralRelayTests.Fixture(root);TemplateForm.Apply(f.Store,f.Policy,"review-project","source","target",0);var p=f.Policy.Projects.Last();Assert(p.Delegation=="explicit"&&p.TargetChannels=="target"&&!f.Policy.Rules.Last().Enabled,"unsafe template defaults");RelayPolicies.ValidateReferences(f.Policy,f.Store);});
        check("configuration diff reports fields instead of raw policy JSON",()=>{var f=new GeneralRelayTests.Fixture(root);var clone=Json.Read<RelayPolicy>(Json.Write(f.Policy));clone.Projects[0].ReturnMode="batch";string diff=ConfigPreviewForm.Difference(f.Policy,clone);Assert(diff.Contains("Remise des résultats")&&!diff.Contains("\"SourceChannels\""),"unreadable diff");});
        check("parent retains writer capacity until Codex confirms its turn ended",()=>{var f=new GeneralRelayTests.Fixture(root);var spec=f.Spec();spec.To="target";spec.Access="write";var parent=f.Submit(spec);f.Adapter.InProgress=true;parent=f.Run(parent);parent.DispatchPhase="work";f.Store.Save(parent);var child=f.Submit();child.Job.Parent=parent.Id;child.ReturnToSource=false;f.Store.Save(child);RelayFamily.Request(f.Store,parent,new RelaySession{Channel=parent.TargetChannelId,Thread=parent.TargetThreadId});Assert(RelayRouter.Executing(f.Store.Message(parent.Id)),"writer capacity released early");f.Adapter.InProgress=false;parent=f.Run(parent);Assert(parent.State=="children"&&!RelayRouter.Executing(parent),"ended parent still holds writer");Assert(!RelayFamily.PrepareResume(f.Store,parent),"resumed with pending child");child.State="completed";child.Outcome="succeeded";child.Result="child evidence";f.Store.Save(child);Assert(RelayFamily.PrepareResume(f.Store,parent)&&parent.State=="queued"&&parent.Continuation.Contains("child evidence"),"parent did not resume");});
        check("only recipient may suspend a parent and children must not independently restart it",()=>{var f=new GeneralRelayTests.Fixture(root);var m=f.Submit();m.State="waiting";m.TargetThreadId="target-chat";m.DispatchPhase="work";f.Store.Save(m);Reject(()=>RelayFamily.Request(f.Store,m,new RelaySession{Channel="other",Thread="target-chat"}));var child=f.Submit();child.Job.Parent=m.Id;f.Store.Save(child);Reject(()=>RelayFamily.Request(f.Store,m,new RelaySession{Channel=m.TargetChannelId,Thread=m.TargetThreadId}));});
        check("temporary cleanup requires ownership and a dead exact process",()=>{var f=new GeneralRelayTests.Fixture(root);string runtime=Path.Combine(f.Folder,"runtime");string owned=Path.Combine(runtime,Guid.NewGuid().ToString("N"));string unknown=Path.Combine(runtime,Guid.NewGuid().ToString("N"));Directory.CreateDirectory(owned);Directory.CreateDirectory(unknown);CacheMaintenance.Mark(owned,Int32.MaxValue,1);Assert(CacheMaintenance.Candidates(f.Folder).SequenceEqual(new[]{owned}),"unowned cache selected");Assert(CacheMaintenance.Clean(f.Folder,new[]{owned,unknown,f.Folder})==1&&Directory.Exists(unknown),"cleanup escaped proof");});
        check("Git worktree preserves dirty source and reuses existing worktree",()=>{var f=new GeneralRelayTests.Fixture(root);string repository=Path.Combine(f.Folder,"repo"),dest=Path.Combine(f.Folder,"isolated");Directory.CreateDirectory(repository);WorkspaceService.Git(repository,"init -q");File.WriteAllText(Path.Combine(repository,"note.txt"),"committed");WorkspaceService.Git(repository,"add note.txt");WorkspaceService.Git(repository,"-c user.name=Fixture -c user.email=fixture@example.test commit -q -m fixture");File.WriteAllText(Path.Combine(repository,"note.txt"),"uncommitted");WorkspaceService.Create(repository,dest,"HEAD");Assert(File.ReadAllText(Path.Combine(dest,"note.txt"))=="committed"&&File.ReadAllText(Path.Combine(repository,"note.txt"))=="uncommitted","dirty source changed");File.WriteAllText(Path.Combine(dest,"note.txt"),"isolated edits");WorkspaceService.Create(repository,dest,"HEAD");Assert(File.ReadAllText(Path.Combine(dest,"note.txt"))=="isolated edits","reused workspace overwritten");});
        check("pause during preparation prevents the subsequent send",()=>{var f=new GeneralRelayTests.Fixture(root);var m=f.Submit();m.OriginVerified=false;f.Store.Save(m);f.Adapter.SourceReadHook=()=>RelayDispatch.Set(f.Store,"paused");m=f.Run(m);Assert(f.Adapter.Created==0&&m.State=="queued"&&m.BlockReason=="paused","paused during read but sent anyway");});
        check("policy revision changed during preparation prevents send",()=>{var f=new GeneralRelayTests.Fixture(root);var m=f.Submit();m.OriginVerified=false;f.Store.Save(m);f.Adapter.SourceReadHook=()=>{f.Policy.Agents.ForEach(a=>a.Enabled=false);f.Save();};m=f.Run(m);Assert(f.Adapter.Created==0&&m.State=="queued"&&m.BlockReason=="policy","revoked during read but sent anyway");});
        check("workspace paths preserve commas and accept one path per line",()=>{var paths=RelayPolicies.Paths("C:\\one,two\r\nC:\\three");Assert(paths.Length==2&&paths[0]=="C:\\one,two","valid path split at comma");});
        check("nonfinite agent quota reserve cannot disable routing checks",()=>{var f=new GeneralRelayTests.Fixture(root);f.Policy.Agents[0].MinRemaining=Double.NaN;Reject(()=>RelayPolicies.Validate(f.Policy,false));});
    }
}
